name: testspring
on: push
jobs: 
    test:
        runs-on: ubuntu-latest

        services:
             postgres:
            # Docker Hub image
              image: postgres
            # Provide the password for postgres
              env:
                POSTGRES_PASSWORD: postgres
                POSTGRES_HOST: postgres
                POSTGRES_PORT: 5432
                POSTGRES_USER: postgres
                POSTGRES_DB: db
            # Set health checks to wait until postgres has started
              ports:
                - 5432:5432
              options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s

        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven    
       
            - name: clear project
              run: mvn clean

            - name: compile the project
              run: mvn compile

            - name: run test case
              run: mvn test
              
            - name: Build with Maven
              run: mvn clean install package
         

            - name: save the artifact 
              run: |
               mkdir staging 
               cp target/*.jar staging

            
            - name: persist the workflow 
              uses: actions/upload-artifact@v4
              with:
                name: java artifact
                path: staging 

         
