name: testspring
on: push
jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven    
       
            - name: clear project
              run: mvn clean

            - name: compile the project
              run: mvn compile

            - name: run test case
              run: mvn test

            - name: Build with Maven
              run: mvn clean install package

            - name: save the artifact 
              run: |
               mkdir staging 
               cp target/*.jar staging

            
            - name: persist the workflow 
              uses: actions/upload-artifact@v4
              with:
                name: java artifact
                path: staging 


            - name: setup a database 
              uses: ikalnytskyi/action-setup-postgres@v7

            - run: psql postgresql://postgres:postgres@localhost:5432/postgres -c "SELECT 1"
            - run: psql service=postgres -c "SELECT 1"
            - run: psql -c "SELECT 1"
              env:
                PGSERVICE: postgres